In [16]:
#Q. No. 01 Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

#Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print ("Original Array:")
print (array)

#Interchange rows and columns (transpose the array)
transposed_array = np.transpose(array)
print ("\nTransposed Array:")
print (transposed_array)

Original Array:
[[50 42 52]
 [54 45 69]
 [ 6 59  2]]

Transposed Array:
[[50 54  6]
 [42 45 59]
 [52 69  2]]


In [17]:
#Q. No. 02 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

import numpy as np

array_1d = np.arange(10)

#Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print ("2x5 array:")
print (array_2x5)

#Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print ("5x2 array:")
print (array_5x2)

2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [18]:
#Q. No. 03 Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

array_4x4 = np.random.rand(4, 4)

#Add a border of zeros around the 4x4 array to make it a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print ("4x4 Array:")
print (array_4x4)
print ("\n6x6 Array with border of zeros:")
print (array_6x6)

4x4 Array:
[[0.83474806 0.51199128 0.45674471 0.9013652 ]
 [0.38025872 0.10180423 0.93105889 0.70892066]
 [0.73633909 0.94192624 0.1714526  0.66457495]
 [0.53885039 0.67601374 0.22761958 0.80788458]]

6x6 Array with border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.83474806 0.51199128 0.45674471 0.9013652  0.        ]
 [0.         0.38025872 0.10180423 0.93105889 0.70892066 0.        ]
 [0.         0.73633909 0.94192624 0.1714526  0.66457495 0.        ]
 [0.         0.53885039 0.67601374 0.22761958 0.80788458 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [19]:
#Q. No. 04 Using NumPy, create an array of integers from 10 to 60 with a step of 5.


import numpy as np

array = np.arange(10, 61, 5)
print (array)

[10 15 20 25 30 35 40 45 50 55 60]


In [2]:
#Q. No. 05 Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

#Wecan create a NumPy array of strings and apply different case transformations to each element using NumPy functions along with Python's string methods.
#Example:

import numpy as np

arr = np.array(['python', 'numpy', 'pandas'])

#Apply different case transformations
uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)
capitalize_arr = np.char.capitalize(arr)

#Print the results
print ("Original array:", arr)
print ("Uppercase:", uppercase_arr)
print ("Lowercase:", lowercase_arr)
print ("Title case:", titlecase_arr)
print ("Capitalize:", capitalize_arr)

Original array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title case: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']


In [3]:
#Q. No. 06 Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np

words = np.array(['hello', 'world', 'numpy'])

#Function to insert spaces between characters of each word
def insert_spaces(word):
    return ' '.join(word)

#Apply the function to each word in the array
spaced_words = np.array([insert_spaces(word) for word in words])

print(spaced_words)

['h e l l o' 'w o r l d' 'n u m p y']


In [4]:
#Q. No. 07 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

#Element-wise addition
addition = array1 + array2

#Element-wise subtraction
subtraction = array1 - array2

#Element-wise multiplication
multiplication = array1 * array2

#Element-wise division
division = array1 / array2

print ("Array 1:\n", array1)
print ("Array 2:\n", array2)
print ("Element-wise Addition:\n", addition)
print ("Element-wise Subtraction:\n", subtraction)
print ("Element-wise Multiplication:\n", multiplication)
print ("Element-wise Division:\n", division)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]
Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [5]:
#Q. No. 08 Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np

identity_matrix = np.eye(5)

#Extract diagonal elements
diagonal_elements = np.diag(identity_matrix)

print ("Identity Matrix:")
print (identity_matrix)
print ("\nDiagonal Elements:")
print (diagonal_elements)

Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [6]:
#Q. No. 09 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

import numpy as np

random_array = np.random.randint(0, 1001, size=100)

#Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

#Filter prime numbers from the array
prime_numbers = np.array([num for num in random_array if is_prime(num)])

print ("Random array:", random_array)
print ("Prime numbers:", prime_numbers)

Random array: [151 293  28 476 465 379 103 601 580 342 642 433 507 228 872 652 914 594
 707  71 587 764 342 421 648 898 423  70  67 212 188 656 103 390 724 360
 216 498 635 850 615 221   8 698 811 981 326 182 661 344 125 159 779 817
 185  93 583 152 535 367 287 477 783 171 344 222  67  58 376 982 930 134
  35 602 772  88 564 785 555 392 215 244  62 800 940 389 437 542 117 517
 450 840 697 651 817  38 560 662 655 138]
Prime numbers: [151 293 379 103 601 433  71 587 421  67 103 811 661 367  67 389]


In [7]:
#Q. No. 10  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

import numpy as np

np.random.seed(0)
daily_temperatures = np.random.uniform(low=10, high=30, size=30)  #Temperatures between 10 and 30 degrees

#Display daily temperatures
print ("Daily temperatures for the month:")
print (daily_temperatures)

#Reshape the array into a 2D array with 5 weeks and 7 days per week
weekly_temperatures = daily_temperatures.reshape(5, 6)

#Calculate weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

#Display weekly averages
print ("\nWeekly averages:")
print (weekly_averages)

Daily temperatures for the month:
[20.97627008 24.30378733 22.05526752 20.89766366 18.47309599 22.91788226
 18.75174423 27.83546002 29.27325521 17.66883038 25.83450076 20.5778984
 21.36089122 28.51193277 11.42072116 11.74258599 10.40436795 26.65239691
 25.56313502 27.40024296 29.57236684 25.98317128 19.22958725 25.61058353
 12.36548852 22.79842043 12.86706575 28.89337834 20.43696644 18.2932388 ]

Weekly averages:
[21.60399447 23.32361483 18.348816   25.55984781 19.27575971]
